### ISSUE TITLE
Add support for custom defined tests

### ISSUE THREAD

**Issue by titom73** [arista-netdevops-community/network-test-automation#118]
## Description

In order to allow users to build their own test collection, it would be nice to add option to support catalog pointing to custom libraries.

Today, we only look at `anta.tests` package but we could extend YAML format to support both `anta.tests` and a custom package with the following format:

```yaml
<package.name>:
      - <test function>:
           <function options>
```

An example would be:

```yaml
anta.tests.software:
  - verify_eos_version: # Verifies the device is running one of the allowed EOS version.
      versions: # List of allowed EOS versions.
        - 4.25.4M
        - 4.26.1F
inetsix.tests.mydesign:
  - check_topology:
```

## Potential impacts:

- `anta.loader.parse_catalog`
